version: '3'
services:
  db:
    image:  postgres:latest
    restart: always
    ports:
      - 32700:5432
    environment:
      POSTGRES_USER:  root
      POSTGRES_PASSWORD:  root
      POSTGRES_DB: social_network
    volumes:
      - '${PWD}/initdb:/docker-entrypoint-initdb.d'

  redis:
    image: redis:latest
    ports:
      - "32701:6379"